package miu.edu.cs.cs525.final_project.bank;

import javax.swing.*;

import miu.edu.cs.cs525.final_project.framework.ui.DepositDialog;

import java.awt.*;

public class JDialog_Deposit extends DepositDialog
{
    

    private BankFrm parentframe;
    private String accnr;
    
	public JDialog_Deposit(BankFrm parent, String aaccnr)
	{
		super(parent);
		parentframe=parent;
		accnr=aaccnr;
		// This code is automatically generated by Visual Cafe when you add
		// components to the visual environment. It instantiates and initializes
		// the components. To modify the code, only use code syntax that matches
		// what Visual Cafe can generate, or Visual Cafe may be unable to back
		// parse your Java file into its visual environment.
		//{{INIT_CONTROLS
		setTitle("Deposit");
		
		JLabel1.setText("Acc Nr");
		getContentPane().add(JLabel1);
		JLabel1.setForeground(Color.black);
		JLabel1.setBounds(12,12,48,24);
		JLabel2.setText("Amount");
		getContentPane().add(JLabel2);
		JLabel2.setForeground(Color.black);
		JLabel2.setBounds(12,48,48,24);
		JTextField_NAME.setEditable(false);
		getContentPane().add(JTextField_NAME);
		JTextField_NAME.setBounds(84,12,144,24);
		
		getContentPane().add(JTextField_Deposit);
		JTextField_Deposit.setBounds(84,48,144,24);
		//}}
	    JTextField_NAME.setText(accnr);

	}



	//{{DECLARE_CONTROLS
	JLabel JLabel1 = new JLabel();
	JLabel JLabel2 = new JLabel();
	JTextField JTextField_NAME = new JTextField();
	
	JTextField JTextField_Deposit = new JTextField();
	//}}


}